@startuml Kasse
skinparam classAttributeIconSize 0

package java {
    package util {
        class UUID
        interface List<T>
    }
    package math {
        class BigDecimal
    }
    package time {
        class LocalDate
    }
}

package com.acme.kms.entity #DDDDDD {
    class Kasse <<entity>> {
        id: UUID
        bezeichnung: String
        kassierer: Kassierer
        bargeldbestand: BigDecimal
        kassenBons: List<KassenBon>
    }

    class Kassierer {
        id: UUID
        vorname: String
        nachnameTest: String
        email: String
    }

    class KassenBon {
        id: UUID
        date: LocalDate
        betrag: BigDecimal
    }

    Kasse *-- "0..*" KassenBon : kassenBons

    Kasse ..> UUID
    Kasse ..> BigDecimal
    Kasse ..> List

    Kassierer ..> UUID
    KassenBon ..> UUID
    KassenBon ..> LocalDate
    KassenBon ..> BigDecimal
}

hide empty members

footer (c) Kilian Schmitt
@enduml
