@startuml Kasse
skinparam classAttributeIconSize 0

package java {
    package util {
        class UUID
        interface List<T>
    }
    package math {
        class BigDecimal
    }
    package time {
        class LocalDate
        class LocalDateTime
    }
}

package jakarta.persistence {
    annotation Entity
    annotation Table
    annotation Id
    annotation GeneratedValue
    annotation Version
    annotation ManyToOne
    annotation OneToMany
}

package org.hibernate.annotations {
    annotation CreationTimestamp
    annotation UpdateTimestamp
}

package com.acme.kms.entity #DDDDDD {
    class Kasse << entity >> << @Entity >> << @Table >> {
        @Id
        @GeneratedValue
        id: UUID
        @Version
        version: int
        bezeichnung: String
        bargeldbestand: BigDecimal
        @CreationTimestamp
        erzeugt: LocalDateTime
        @UpdateTimestamp
        aktualisiert: LocalDateTime
    }

    class Kassierer << entity >> << @Entity >> {
        @Id
        @GeneratedValue
        id: UUID
        vorname: String
        nachname: String
        email: String
    }

    class KassenBon << entity >> << @Entity >> {
        @Id
        @GeneratedValue
        id: UUID
        datum: LocalDate
        betrag: BigDecimal
    }

    Kasse *-- "1" Kassierer : @ManyToOne \n kassierer
    Kasse *-- "0..*" KassenBon : @OneToMany \n kassenBons

    Kasse ..> UUID
    Kasse ..> BigDecimal
    Kasse ..> List
    Kasse ..> LocalDateTime
    Kasse .up.> Entity
    Kasse .up.> CreationTimestamp

    Kassierer ..> UUID
    KassenBon ..> UUID
    KassenBon ..> LocalDate
    KassenBon ..> BigDecimal
}

hide empty members

footer (c) Kilian Schmitt
@enduml
